[package]
name = "chirrtl-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
logos = "0.12"
lalrpop-util = { version = "0.21.0", features = ["lexer", "unicode"] }
serde_json = "1.0.139"
num-bigint = "0.4.6"
num-traits = "0.2.19"
thiserror = "2.0.12"

[build-dependencies]
lalrpop = "0.22.1"
