[package]
name = "chirrtl-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
logos = "0.12"
lalrpop-util = { version = "0.21.0", features = ["lexer", "unicode"] }

[build-dependencies]
lalrpop = "0.22.1"
